### ISSUE TITLE
Network events not getting registered in DB

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#10]
The problem is in this line :

https://github.com/zdresearch/OWASP-Honeypot/blob/cca5081bc828fed0ca195e36a07a97b127125e84/core/network.py#L105

the ip is getting splitted but the type(ip) is bytes and then ```shell netaddr.valid_ipv4(ip) ``` always fails because of that ,so in my local computer i just converted it by `ip=ip.decode('utf-8')` .
```shell netaddr.valid_ipv4(ip) ```  does not work when ip is a type 'byte',it needs a string.
Because even if the ip is valid it is not getting registered in db because of the if condition failure
@Ali-Razmjoo : you could add the changes for this bug or i can send a PR of this change .

**Comment by Ali-Razmjoo** [comment]
@dhirensr thanks for the report, please send your PR.
