### ISSUE TITLE
OSCHMOD package not in requirements.txt

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#125]
when running python3 oh.py --test I got a package error for oschmod which is imported here (https://github.com/zdresearch/OWASP-Honeypot/blob/master/core/file_monitor.py#L5) 
but I'm wondering is this my local machine problem because the same command is not failing in github actions , hence creating an issue for confirmation of the same.

**Comment by ChakshuGupta** [comment]
This package is already there in the requirements.txt

**Comment by dhirensr** [comment]
@ChakshuGupta  Thanks for the clarification. somehow missed it.
