### ISSUE TITLE
top honeypot_machine name and network_machine name route. Needed?

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#15]
Hello @Ali-Razmjoo again,
I saw that we also want 2 routes stating top network machine_name and  top honeypot machine_name,and the logic would be 
honeypot/network_event -> count -> sortby count
but my question is when the machine name is getting inserted in database it is taking from 
https://github.com/zdresearch/OWASP-Honeypot/blob/6e3b71cac9869c0b4c1a56e238210d0f951d1a0f/config.py#L49
and it is never changing in the code ,so basically wouldn't it be just find :
 machine_name: real_identifier_machine_name
 and you wont get more than 1 record in top machine names ?
i just want clarification on this and then would work on it.

**Comment by Ali-Razmjoo** [comment]
for the first question yes, it's good to have those api and for the second part, this honeypot designed to use on multiple servers, for example one server with ip x1 in country y1 and ip x2 and country y2 both can connect to the same database in ip x3 and country y3, so we can define which request come from which machine.


I am planning to set it up on different regions in aws, and make a live version for this framework, then I need to use one master database and seperate the request to see what attack come from which machine if needed.
