### ISSUE TITLE
Table sorting and search are not functional anymore

### ISSUE THREAD

**Issue by ChakshuGupta** [zdresearch/OWASP-Honeypot#168]
The sort and search options stopped working after switching to server side pagination option. Need to fix this.

![image](https://user-images.githubusercontent.com/6474622/92373817-2f5a5f80-f0ff-11ea-9c42-4096ead12d19.png)

**Comment by Ali-Razmjoo** [comment]
@ChakshuGupta can you take a look when you have time? I didn't figure out the issue (didn't find error, it just stopped working)

**Comment by ChakshuGupta** [comment]
@Ali-Razmjoo Yeah sure.
