### ISSUE TITLE
ModuleNotFoundError: No module named 'terminable_thread'

### ISSUE THREAD

**Issue by aleixvaz** [zdresearch/OWASP-Honeypot#177]
Hi,
When I tried to deploy the Honeypot with the following command _python3 ohp.py_ (default configuration), I got this error message:

```
Traceback (most recent call last):
  File "ohp.py", line 5, in <module>
    from core.load import load_honeypot_engine
  File "/home/aleix/Documentos/OWASP-Honeypot/core/load.py", line 11, in <module>
    from terminable_thread import Thread, threading
ModuleNotFoundError: No module named 'terminable_thread'
```

Is there anything I'm missing?

**Comment by dhirensr** [comment]
hello @aleixvaz ,
have you installed terminable_thread package? 
you could just install all the necessary packages by,
```
pip install -r requirements.txt
```

**Comment by aleixvaz** [comment]
Yes, I did. All of them were installed.

**Comment by Ali-Razmjoo** [comment]
also make sure your pip and python is version 3+
