### ISSUE TITLE
program title for cmd args

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#20]
Hello @Ali-Razmjoo ,
I noticed that the program title for command line is Nettacker which I believe is another project where it is taken from,
https://github.com/zdresearch/OWASP-Honeypot/blob/5935ba5356cad95a4e580d4c04901d83789de532/core/load.py#L470

shouldn't you change it to Honeypot?

**Comment by Ali-Razmjoo** [comment]
yes, I used Nettacker pattern for this xD, well that's awkward, thanks for your report, will fix it up myself.
