### ISSUE TITLE
Top honeypot/network events ports by country

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#24]
The logic of the route is 

honeypot_events-> country-> top ports
network_events-> country-> top ports

**Comment by dhirensr** [comment]
@Ali-Razmjoo : should i also send for top ports by date also?
and also please reply on https://github.com/zdresearch/OWASP-Honeypot/issues/26 also

**Comment by Ali-Razmjoo** [comment]
yes go ahead...

**Comment by dhirensr** [comment]
@Ali-Razmjoo : https://github.com/zdresearch/OWASP-Honeypot/pull/29
And also i sent you a mail waiting for a reply there .
