### ISSUE TITLE
Regarding the replacement of tshark with python port sniffing

### ISSUE THREAD

**Issue by tulja** [zdresearch/OWASP-Honeypot#28]
Hello @Ali-Razmjoo, I came across **todo** in the core/network.py regarding the replacement of tshark with python port sniffing (e.g. https://www.binarytides.com/python-packet-sniffer-code-linux), I would like to work on it. Please let me know if I can work on it.

**Comment by dhirensr** [comment]
@tulja @Ali-Razmjoo : i also saw that the link in the todo explicitly says that if we just follow this ,it could break things for Windows as this doesn't support Windows OS.
and there are also other options available like https://github.com/dugsong/pypcap
what do you'll think?

**Comment by tulja** [comment]
The Socket creation is different for Windows and Linux, but we can add appropriate check for the platform using (https://stackoverflow.com/questions/110362/how-can-i-find-the-current-os-in-python) and perform neccessary packet filtering. I tested it on Windows 8.1 and Ubuntu 16.04, with few checks I'm able to run the same code for both Windows and Linux. If we use external packages (which internally have few issues like https://github.com/dugsong/pypcap/issues) things may break. I think it is better option to go with raw_socket with proper checks, @Ali-Razmjoo  Please let me know what you think

**Comment by tulja** [comment]
The Socket creation is different for Windows and Linux, but we can add appropriate check for the platform using (https://stackoverflow.com/questions/110362/how-can-i-find-the-current-os-in-python) and perform neccessary packet filtering. I tested it on Windows 8.1 and Ubuntu 16.04, with few checks I'm able to run the same code for both Windows and Linux. If we use external packages (which internally have few issues like https://github.com/dugsong/pypcap/issues) things may break. I think it is better option to go with raw_socket with proper checks, @Ali-Razmjoo Please let me know what you think

**Comment by Ali-Razmjoo** [comment]
if the performance is better, I'm in.
