### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#3]
Hello,
for installation wiki I would like to improve the docs saying that for ubuntu : "sudo apt-get install tshark
" and other instructions instead of just specifying install tshark .
I would like to improve docs and would send a pull requests once you reply,because i dont know if someone is already working on it.

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for your feedback, I will update wiki in a few days... please let me know if any more changes/adds required.

thanks.

**Comment by dhirensr** [comment]
@Ali-Razmjoo  : thanks for replying! i had also sent an email to you regarding gsoc 2019 contribution! I want to contribute to OWASP/Honeypot for GSOC 2019 so what do i do next to understand the codebase better?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : we could add what are honeypot events in the wiki for context! because i didnt knew much about it ,then I found it interesting! 
maybe this link : https://en.wikipedia.org/wiki/Honeypot_(computing)
