### ISSUE TITLE
store_network_captured_files flag used?

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#31]
Hello @Ali-Razmjoo ,
I just saw that there is a flag in network configuration  store_network_captured_files and it's set default to False,but I didn't see it being used anywhere in the codebase.
I don't know whether it's bug or the feature doesn't exists in the codebase.
Just wanted to know if it's a feature,what should it do ? so I can take up this task.

**Comment by dhirensr** [comment]
@Ali-Razmjoo : waiting for your reply on some of the tickets and a PR

**Comment by sagnik-chatterjee** [comment]
If this is not assigned , can i take up this issue ?

**Comment by dhirensr** [comment]
@Ali-Razmjoo : please reply

**Comment by Ali-Razmjoo** [comment]
This feature meant to be added later https://github.com/zdresearch/OWASP-Honeypot/wiki/Installation

* Network Packet Analyzer (Basic/ ~~Advance~~ )
* ~~Hacker Activity Monitor~~

Advanced packet analysis needed more information from the network, and process it real time was kind of hard, maybe we can add a new thread and do it passively and insert the data to the database?

which it drives us to a "log explorer" and then dived logs by honeypot, network, advanced (with much network details).

to not do any duplicated work maybe we can separated issue/featureticket in GitHub and anyone whois workiing on this can give us a heads up?

**Comment by sagnik-chatterjee** [comment]
hi i was not able to reproduce this ..

**Comment by Ali-Razmjoo** [comment]
@sagnik-chatterjee what do you mean?
