### ISSUE TITLE
Typo in Usage Wiki page

### ISSUE THREAD

**Issue by mzfr** [zdresearch/OWASP-Honeypot#51]
On [Usage](https://github.com/zdresearch/OWASP-Honeypot/wiki/Usage) page there is a typo in the very beginning, it's says `Nettacker` instead it should read `OWASP Honeypot`

**Comment by dhirensr** [comment]
@mzfr : thank you for pointing out. I or @Ali-Razmjoo  will update in the documentation.
In the code it's already updated in this ticket https://github.com/zdresearch/OWASP-Honeypot/issues/20

**Comment by Ali-Razmjoo** [comment]
thanks for the report, here is the consequence of copy and paste 👍
