### ISSUE TITLE
python3 ohp.py fails in some docker image

### ISSUE THREAD

**Issue by dhirensr** [zdresearch/OWASP-Honeypot#6]
OS : Ubuntu 18.04 
Type : Virtual Machine
Steps to reproduce: python3 ohp.py --verbose

It shows : 
```shell
Successfully tagged ohp_httpserver:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint ohp_sshserver_strong_password (8ca84e650f147501953a159707c9c0386af8971ae82292e753fd0dd52c14b5da): Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use.


[+] [2019-02-13 18:52:37] creating image ohp_httpserver
[+] [2019-02-13 18:53:00] image ohp_httpserver created
[+] [2019-02-13 18:53:01] container ohp_ftpserver_strong_password started, forwarding 0.0.0.0:21 to 172.18.0.2:21
[+] [2019-02-13 18:53:01] container ohp_sshserver_strong_password started, forwarding 0.0.0.0:22 to CANNOT_FIND_IP_ADDRESS:22
[+] [2019-02-13 18:53:03] container ohp_httpserver_basic_auth_strong_password started, forwarding 0.0.0.0:80 to 172.18.0.3:80
```

@Ali-Razmjoo  : please reply about this ,because i am not able to configure honeypot on my local machine due to this ,no events are getting registered in db.

**Comment by Ali-Razmjoo** [comment]
Hi,

it's because you are running the agent on your machine and the machine already is using port 22 for your own ssh server!

you should stop ssh server on your machine or change `real_machine_port_number` in the config file. https://github.com/zdresearch/OWASP-Honeypot/blob/master/lib/modules/ssh/__init__.py#L16

please let me know if you have more questions.

Regards.

**Comment by dhirensr** [comment]
Hello,
Thank you for the quick reply that worked ! however i get this error 
```shell
    ignore_ip_addresses.extend(get_gateway_ip_addresses(configuration))
  File "/home/dhirensr/OWASP-Honeypot/core/network.py", line 36, in get_gateway_ip_addresses
    ).read().rsplit()[0].replace("\'", "")
IndexError: list index out of range
```
and i fixed it just by removing the split and now it works fine.
I don't know if this is the correct fix or could you explain what we need there?
Because i am getting a list of just 1 ip and it does not makes sense to split it.
@Ali-Razmjoo : waiting for your reply.

**Comment by Ali-Razmjoo** [comment]
it returns this error ONLY if you don't change the port and your container has not an IP address.

in case of error:
```
In [9]: os.popen(
   ...:             "docker inspect -f '{{{{range.NetworkSettings.Networks}}}}"
   ...:             "{{{{.Gateway}}}}{{{{end}}}}' {0}".format(container_name)
   ...:         ).read()
Error: No such object: ohp_httpserver_strong_password
Out[9]: '\n'
```

otherwise:
```
In [12]: os.popen(
    ...:             "docker inspect -f '{{{{range.NetworkSettings.Networks}}}}"
    ...:             "{{{{.Gateway}}}}{{{{end}}}}' {0}".format(container_name)
    ...:         ).read()
Out[12]: '172.18.0.1\n'
```

if you are still getting an error, please copy the whole printed stuff on your terminal/cmd.

thanks.

**Comment by dhirensr** [comment]
Yes the output given by you is right! so here my output of 
```shell
print(os.popen(
            "docker inspect -f '{{{{range.NetworkSettings.Networks}}}}"
            "{{{{.Gateway}}}}{{{{end}}}}' {0}".format(container_name)
        ).read().rsplit())
```

output : 
```
['172.18.0.1']
[]
['172.18.0.1']
```

@Ali-Razmjoo : so the split[0] fails when the list is empty,and then it's not checked as a condition.

**Comment by dhirensr** [comment]
fixed in  https://github.com/zdresearch/OWASP-Honeypot/pull/8
