### ISSUE TITLE
Gateway IP of the docker printed in the top ten user and password section of the api server.

### ISSUE THREAD

**Issue by AlphaRoy14** [zdresearch/OWASP-Honeypot#63]
In the bottom of the page of the API server, where top 10 username and passwords are shown of the various modules, the IP of the docker gateway(eg 172.18.0.1) is printed instead of IP of source. Please let me know if this is an intended behavior or else I can work on it.

**Comment by dhirensr** [comment]
@AlphaRoy14 :  Thanks for reporting the issue.
Ip addresses are logged inside the docker container and hence it's going in the database as IP of the docker gateway.
You can start seeing module file for SSH/strong_password (https://github.com/zdresearch/OWASP-Honeypot/blob/master/lib/modules/ssh/strong_password/files/ssh_listener.py#L19) and feel free to send a PR if you fix the issue

**Comment by Ali-Razmjoo** [comment]
I think it's because of the test environment, if you do it with valid IP it will not have the same issue. 

```
root@ip-172-31-22-154:/home/ubuntu/owasp-honeypot# docker inspect ohp_sshserver_strong_password
[
    {
,....

                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
```
events are with my machine ip: 172.31.22.154
```
 {u'_id': ObjectId('5e5713dd8be95e9642bf13b1'),
  u'country_ip_dest': u'-',
  u'country_ip_src': u'SE',
  u'date': u'2020-02-27 00:57:00',
  u'event_type': u'honeypot_event',
  u'ip_dest': u'172.31.22.154',
  u'ip_src': u'78.71.xx.xx',
  u'machine_name': u'stockholm_server_1',
  u'module_name': u'ssh/strong_password',
  u'port_dest': 23,
  u'port_src': 55867}]
```

**Comment by Ali-Razmjoo** [comment]
if that answer your question, feel free to close the issue, or let us know if you have any more questions.
