### ISSUE TITLE
Tshark displays destination IP and source Port.

### ISSUE THREAD

**Issue by AlphaRoy14** [zdresearch/OWASP-Honeypot#64]
The tshark command given [here](https://github.com/zdresearch/OWASP-Honeypot/blob/500cabd8cca54a1d743b3c3b0c4d0b919e5201be/core/network.py#L93) captures destination IP and source Port. Doesn't displaying IP of source and port of destination make more sense? I tried changing the command to `tshark -Y "ip.dst != xyz.xyz.xyz.xyz" -T fields -e ip.src -e tcp.dstport` but there's no difference  in output. Probably because everything is running locally and there's no external IP trying to connect to it.

**Comment by Ali-Razmjoo** [comment]
potential awkward bug, I've to check and get back to you. thanks for reporting.

**Comment by Ali-Razmjoo** [comment]
ok, I remember what I did there, so if you run tshark and look into requests, there are two kind, incoming and outgoing. instead oof capture incoming I am capturing outgooing which is not wrong, but it's not right too.

```
root@9eb6f3ce0289:/# tshark -l -V -T fields -e ip.dst -e ip.src -e tcp.srcport -e tcp.dstport -ni any
Running as user "root" and group "root". This could be dangerous.
Capturing on 'any'
172.17.0.3	172.17.0.1	48034	80
172.17.0.1	172.17.0.3	80	48034
```

so outgoing and incoming has exact opposite src and dest. and I used hacky wrong way to split them...

```
 try:
                        ip, port = str(line.rsplit()[0].decode()), int(line.rsplit()[1])
                    except Exception as _:
                        ip, port = None, None
                    # check if event shows an IP
                    if (netaddr.valid_ipv4(ip) or netaddr.valid_ipv6(ip)) \
                            and ip not in ignore_ip_addresses \
                            and port not in ignore_ports:  # ignored ip addresses and ports in python - fix later
                        # check if the port is in selected module
```

also that comment meant to be for this issue and I totally forget about.


so I will try to fix it soon and do the right way....

thanks for bringing this up.

**Comment by AlphaRoy14** [comment]
I see! In the above case the incoming and outgoing ports are same. However, AFAIK the incoming port (client side) is chosen at random by the OS. Since we already have the code to parse ip and port, I think if we just change the command to view destination port `tshark -l -V -T fields -e ip.src -e tcp.dstport` the issue can be solved. If there's something that I'm missing please let me know!

**Comment by Ali-Razmjoo** [comment]
I did some changes in #65, hopefully is now much less confusing?

**Comment by AlphaRoy14** [comment]
Thanks! less confusing now.
