### ISSUE TITLE
killing python 2.7 threads issue

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Honeypot#66]
seems it sometimes not working on py2.7 and it messes up the CI https://github.com/zdresearch/OWASP-Honeypot/blob/master/core/exit_helper.py#L31-L60

**Comment by dhirensr** [comment]
@Ali-Razmjoo : I was thinking we should now remove support for python2 as it's officially not supported anymore

**Comment by Ali-Razmjoo** [comment]
i used `terminable_thread`, hopefully that will work... didn't get any issue so far.
