### ISSUE TITLE
log explorer

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Honeypot#67]
It would be nice to have a log explorer in webui with search and export features.

**Comment by amanjiofficial** [comment]
Hey @Ali-Razmjoo @dhirensr I am working on this issue. For the export feature I think we can give option to create csv of the logs and export it. For the search option IP based, username based, password based search will be appropriate. Suggestions please @Ali-Razmjoo @dhirensr. Thank you

**Comment by Ali-Razmjoo** [comment]
@amanjiofficial go ahead
