### ISSUE TITLE
refactor and clean /api

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Honeypot#69]
the files in /api are not clean at all and it's very hard to understand what are they doing... need a good refactor and a better in code docs, specially database_queries.py, server.py

**Comment by dhirensr** [comment]
@Ali-Razmjoo : any suggestions for the same? 
Because I see it's already seperated in database_queries and server.py is using the same.

**Comment by Ali-Razmjoo** [comment]
no, didn't think it through yet... just looked messy at the first sight.

**Comment by ChakshuGupta** [comment]
@Ali-Razmjoo I would like to take up this issue. How should I proceed with this? What kind of refactoring did you have in mind?

**Comment by Ali-Razmjoo** [comment]
just make it easier to understand... nothing in my mind.

**Comment by Ali-Razmjoo** [comment]
maybe this helps https://github.com/zedr/clean-code-python

**Comment by ChakshuGupta** [comment]
Thansk. I'll start on it.

**Comment by amanjiofficial** [comment]
Is anybody still working on this? @ChakshuGupta @Ali-Razmjoo

**Comment by ChakshuGupta** [comment]
@amanjiofficial I had started working on it. Busy with exams at the moment. Will start again afterwards.
