### ISSUE TITLE
update wiki docs

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Honeypot#70]
* add developers guideline
* add database/connection.py documents `credential_events, honeypot_events_data, honeypot_events, network_events`
* add module specific document (ics, http, etc)
....

**Comment by dhirensr** [comment]
@Ali-Razmjoo : I will update it by this weekend

**Comment by amanjiofficial** [comment]
I would like to work on this issue if its still up @dhirensr @Ali-Razmjoo

**Comment by Ali-Razmjoo** [comment]
I think @dhirensr is taking care of it, right?

**Comment by dhirensr** [comment]
@amanjiofficial : I am working on it.

**Comment by dhirensr** [comment]
@Ali-Razmjoo : we can close this ticket as all the documentation mentioned is done!

**Comment by Ali-Razmjoo** [comment]
thanks @dhirensr
