### ISSUE TITLE
Adding API on Web UI

### ISSUE THREAD

**Issue by amanjiofficial** [zdresearch/OWASP-Honeypot#77]
We can create scope for using API endpoints [https://github.com/zdresearch/OWASP-Honeypot/wiki/API](url) on the separate views on front end Web UI. Suggestions please @Ali-Razmjoo @dhirensr

**Comment by dhirensr** [comment]
@amanjiofficial : what do you mean here ? could you elaborate?
from what I understood is that, for each API it doesn't makes sense to create a sepearate a frontend I think.
there would be as many pages as the number of routes and 1 page for 1 route is too less I think.

**Comment by amanjiofficial** [comment]
I mean that we can create different type of reports by clubbing similar type of APIs so that the user can  export such reports and have better analysis of the data and also on web UI user can query data with date parameter for better and customized visualization of results.

**Comment by Ali-Razmjoo** [comment]
for first release we can cover #67 and #122 and then we decide for farther changes.
