### ISSUE TITLE
Adding SMTP Module

### ISSUE THREAD

**Issue by amanjiofficial** [zdresearch/OWASP-Honeypot#78]
We can add smtp module by creating a smtp server with [https://pypi.org/project/aiosmtpd/](url) and creating event logs. Suggestions @dhirensr @Ali-Razmjoo

**Comment by dhirensr** [comment]
@amanjiofficial :  I was also planning to add this module this GSOC if I get selected. but I think it's fine for me if you want to add this,I could add some different module.
@Ali-Razmjoo : what do you think?

**Comment by Ali-Razmjoo** [comment]
bravo.
